repos:
  # - repo: https://github.com/psf/black
  #   rev: 20.8b1
  #   hooks:
  #     - id: black
  #       language_version: python3.9

  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.7.0
  #   hooks:
  #     - id: isort
  #       args: [--filter-files]
  #       files: \.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
