name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test app"

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          path: ./pyVoice

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup the server, install dependencies
        run: |
          cd pyVoice
          sudo chmod +x scripts/setup_linux.sh
          ./scripts/setup_linux.sh

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-path: ~/.virtualenvs
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: Install Poetry dependencies
        run: |
          cd pyVoice
          poetry install

      - name: Run pyTest
        continue-on-error: true
        id: pytest
        run: |
          cd pyVoice
          poetry run pytest --html=test-report.html --self-contained-html

      - name: Upload test report to artifacts
        # if: steps.pytest.outcome != 'success' || steps.pytest.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: pyVoice/test-report.html

      - name: Notify
        uses: ShaunLWM/action-pushbullet@master
        if: steps.pytest.outcome == 'success'
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: pyVoice Tests  - Sucess
          PB_TEXT: The pyVoice repo has been tested with no errors!
