name: Weekly Git logs

on:
  schedule:
    # every friday at 20:30
    - cron: "00 20 * * 5"

  workflow_dispatch:

jobs:
  export_git_logs:
    runs-on: ubuntu-latest
    name: "Export weekly Git logs"

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          repository: pyVoice/pyVoice
          path: ./pyVoice
          fetch-depth: 0

      - name: Checkout site-pap repository
        uses: actions/checkout@v2
        with:
          repository: pyVoice/site-pap
          path: ./site-pap
          fetch-depth: 0

      - name: Checkout device-api repository
        uses: actions/checkout@v2
        with:
          repository: pyVoice/device-api
          path: ./device-api
          fetch-depth: 0

      - name: Get logs for main repository
        run: |
          cd ./pyVoice
          git log --since="7 days ago" --pretty=format:"%h;%an;%ad;%s" > ../log_main.csv

      - name: Get logs for site-pap repository
        run: |
          cd ./site-pap
          git log --since="7 days ago" --pretty=format:"%h;%an;%ad;%s" > ../log_site-pap.csv

      - name: Get logs for device-api repository
        run: |
          cd ./device-api
          git log --since="7 days ago" --pretty=format:"%h;%an;%ad;%s" > ../log_device-api.csv

      - name: Add main repository log to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: git_logs
          path: |
            log_main.csv
            log_site-pap.csv
            log_device-api.csv

      - name: Notify
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: Git logs exported!
          PB_TEXT: The pyVoice repo weekly logs have been exported.
