name: Test the Application

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Install environment and test"
    strategy:
      matrix:
        python-version:
          - 3.9

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          path: ./pyVoice

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Setup the server, install dependencies
        run: |
          cd pyVoice
          sudo chmod +x scripts/setup_linux.sh
          ./scripts/setup_linux.sh

      - name: Setup Poetry environment
        run: |
          cd pyVoice
          pip install -U setuptools wheel poetry
          poetry install

      - name: Run pyTest
        run: |
          cd pyVoice
          poetry shell
          pytest --html=test-report.html --self-contained-html

      - name: Upload test report to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: test-report.html

      - name: Notify
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: pyVoice Tests  - Sucess
          PB_TEXT: The pyVoice repo has been tested successfully!
