name: PEP Analysis
on: [push, pull_request]

defaults:
  run:
    working-directory: ./src

jobs:
  qa:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9.1
      # - name: Run Unit Tests
      #  run: |
      #    pip install pytest
      #    pytest
      - name: Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@0.14.1
        continue-on-error: true
        with:
          reporter: "github-pr-review"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
